import { ComponentType, SearchTypes } from "./SearchTypes";

export class SearchDefs{

  private vaccineComponents: ComponentType[];
  private medraComponents: ComponentType[];

  constructor() {
    this.vaccineComponents = [  
    
      { // Immunizing Agent
        id: 'vaccince_immunizingAgent',
        type: SearchTypes.Lookup,
        groupId: -1,
        displayName: "Immunizing Agent",
        fieldName: 'caefiss_english_value',
        entityName: "caefiss_cd_immunizing_agents_mls",
        parentEntityName: 'caefiss_aefi_vaccines',
        parentEntityId: 'caefiss_id',
        from: 'caefiss_cd_immunizing_agents_mlid',
        to: 'caefiss_vac_cd_immunizing_agents_ml', 
        alias: '',
        isMultiSelect: true,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      },
    
      { // Trade Name
        type: SearchTypes.Lookup,
        id: 'vaccine_tradeName',
        groupId: -1,
        displayName: "Trade name",
        fieldName: "caefiss_vac_immunizing_agent_trade_name_en",
        entityName: "caefiss_cd_immunizing_agents_mls",
        parentEntityName: "caefiss_aefi_vaccines",
        parentEntityId: "caefiss_id",
        from: "caefiss_cd_immunizing_agents_mlid", 
        to: "caefiss_vac_cd_immunizing_agents_ml",
        alias: '',
        isMultiSelect: true,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      },
    
      { // Manufacturer
        type: SearchTypes.Lookup,
        id: 'vaccine_manufacturer',
        groupId: -1,
        displayName: "Manufacturer",
        fieldName: "caefiss_vac_immunizing_agent_manufactureren",
        entityName: "caefiss_cd_immunizing_agents_mls",
        parentEntityName: "caefiss_aefi_vaccines",
        parentEntityId: "caefiss_id",
        from: "caefiss_cd_immunizing_agents_mlid",
        to: "caefiss_vac_cd_immunizing_agents_ml",
        alias: '',
        isMultiSelect: true,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      },
      
      { //Lot Number
        type: SearchTypes.Text,
        id: 'vaccine_lotNumber',
        groupId: -1,
        displayName: "Lot Number", 
        fieldName: "caefiss_lot_number",
        entityName: "caefiss_aefi_vaccines",
        parentEntityName: "incident",
        parentEntityId: '',
        from: "caefiss_case",
        to: "incidentid",
        alias: '',
        isMultiSelect: false,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      },
    
      {// Dose Number
        type: SearchTypes.Option,
        id: 'vaccine_doseNumber',
        groupId: -1,
        displayName: "Dose #",
        entityName: "caefiss_aefi_vaccines",
        from: "caefiss_case",
        parentEntityName: "incident",
        parentEntityId: '',
        to: "incidentid",
        fieldName: "caefiss_vac_dose",
        alias: '',
        isMultiSelect: true,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      },
    
      { //Dosage 
        type: SearchTypes.Number,
        id: 'vaccine_dosage',
        groupId: -1,
        displayName: "Dosage",
        fieldName: "caefiss_vac_dosage",
        entityName: "caefiss_aefi_vaccines",
        parentEntityName: "incident",
        parentEntityId: '',
        from: "caefiss_case",
        to: "incidentid",
        alias: '',
        isMultiSelect: false,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      },
    
      { //Dosage unit
        type: SearchTypes.Option,
        id: 'vaccine_dosageUnit',
        groupId: -1,
        displayName: "Dosage Unit",
        fieldName:"caefiss_vac_dose_unit",
        entityName: "caefiss_aefi_vaccines",
        parentEntityName: "incident",
        parentEntityId: '',
        from: "caefiss_case",
        to: "incidentid",
        alias: '',
        isMultiSelect: true,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      },
    
      {// Route
        type: SearchTypes.Option,
        id: 'vaccine_route',
        groupId: -1,
        displayName: "Route", 
        fieldName: "caefiss_vac_route",
        entityName: "caefiss_aefi_vaccines",
        parentEntityName: "incident",
        parentEntityId: '',
        from: "caefiss_case",
        to: "incidentid",
        alias: '',
        isMultiSelect: true,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      },
    
      { //Site
        type: SearchTypes.Option,
        id: 'vaccine_site',
        groupId: -1,
        displayName: "Site",
        fieldName: "caefiss_vac_site",
        entityName: "caefiss_aefi_vaccines",
        parentEntityName: "incident",
        parentEntityId: '',
        from: "caefiss_case",
        to: "incidentid",
        alias: '',
        isMultiSelect: true,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      }
    ];

    this.medraComponents = [
      { //Verbatim 
        id: 'medra_verbatim',
        type: SearchTypes.Text,
        groupId: -1,
        displayName: "Verbatim",
        fieldName: 'caefiss_verbatim',
        entityName: "caefiss_aefi_meddras",
        parentEntityName: 'incident',
        parentEntityId: '',
        from: 'caefiss_case_to_aefi_meddra',
        to: 'incidentid', 
        alias: '',
        isMultiSelect: false,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      },
      { // LLT
        id: 'medra_llt',
        type: SearchTypes.Lookup,
        groupId: -1,
        displayName: "LLT",
        fieldName: 'caefiss_llt_term_en',
        entityName: "caefiss_cd_meddra_mls",
        parentEntityName: 'caefiss_aefi_meddras',
        parentEntityId: '',
        from: 'caefiss_cd_meddra_mlid',
        to: 'caefiss_meddra_llt_ml', 
        alias: '',
        isMultiSelect: true,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      },
      { // PT 
        id: 'medra_pt',
        type: SearchTypes.Lookup,
        groupId: -1,
        displayName: "PT",
        fieldName: 'caefiss_pt_term_en',
        entityName: "caefiss_cd_meddra_mls",
        parentEntityName: 'caefiss_aefi_meddras',
        parentEntityId: '',
        from: 'caefiss_cd_meddra_mlid',
        to: 'caefiss_meddra_llt_ml', 
        alias: '',
        isMultiSelect: true,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      },
      { // SOC 
        id: 'medra_soc',
        type: SearchTypes.Lookup,
        groupId: -1,
        displayName: "SOC",
        fieldName: 'caefiss_soc_term_en',
        entityName: "caefiss_cd_meddra_mls",
        parentEntityName: 'caefiss_aefi_meddras',
        parentEntityId: '',
        from: 'caefiss_cd_meddra_mlid',
        to: 'caefiss_meddra_llt_ml', 
        alias: '',
        isMultiSelect: true,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      },      
      { // Time interval - Mins 
        id: 'medra_time_interval_mins',
        type: SearchTypes.Number,
        groupId: -1,
        displayName: "Tine Interval - Mins",
        fieldName: 'caefiss_ti_mins',
        entityName: "caefiss_aefi_meddras",
        parentEntityName: 'incident',
        parentEntityId: '',
        from: 'caefiss_case_to_aefi_meddra',
        to: 'incidentid', 
        alias: '',
        isMultiSelect: false,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      },      
      { // Time interval - Hours 
        id: 'medra_time_interval_hours',
        type: SearchTypes.Number,
        groupId: -1,
        displayName: "Tine Interval - Hours",
        fieldName: 'caefiss_ti_hours',
        entityName: "caefiss_aefi_meddras",
        parentEntityName: 'incident',
        parentEntityId: '',
        from: 'caefiss_case_to_aefi_meddra',
        to: 'incidentid', 
        alias: '',
        isMultiSelect: false,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true 
      },      
      { // Time interval - Days
        id: 'medra_time_interval_days',
        type: SearchTypes.Number,
        groupId: -1,
        displayName: "Tine Interval - Days",
        fieldName: 'caefiss_ti_days',
        entityName: "caefiss_aefi_meddras",
        parentEntityName: 'incident',
        parentEntityId: '',
        from: 'caefiss_case_to_aefi_meddra',
        to: 'incidentid', 
        alias: '',
        isMultiSelect: false,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      },      
      
      { // Duration - Mins 
        id: 'medra_duration_mins',
        type: SearchTypes.Number,
        groupId: -1,
        displayName: "Duration - Mins",
        fieldName: 'caefiss_dur_mins',
        entityName: "caefiss_aefi_meddras",
        parentEntityName: 'incident',
        parentEntityId: '',
        from: 'caefiss_case_to_aefi_meddra',
        to: 'incidentid', 
        alias: '',
        isMultiSelect: false,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      },      
      { // Duration - Hours 
        id: 'medra_duration_hours',
        type: SearchTypes.Number,
        groupId: -1,
        displayName: "Duration - Hours",
        fieldName: 'caefiss_dur_hours',
        entityName: "caefiss_aefi_meddras",
        parentEntityName: 'incident',
        parentEntityId: '',
        from: 'caefiss_case_to_aefi_meddra',
        to: 'incidentid', 
        alias: '',
        isMultiSelect: false,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true 
      },      
      { // Duration - Days
        id: 'medra_duration_days',
        type: SearchTypes.Number,
        groupId: -1,
        displayName: "Duration - Days",
        fieldName: 'caefiss_dur_days',
        entityName: "caefiss_aefi_meddras",
        parentEntityName: 'incident',
        parentEntityId: '',
        from: 'caefiss_case_to_aefi_meddra',
        to: 'incidentid', 
        alias: '',
        isMultiSelect: false,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true 
      },      
      { // Duration - D(NYR) 
        id: 'medra_duration_dnyr',
        type: SearchTypes.Number,
        groupId: -1,
        displayName: "Duration - D(NYR)",
        fieldName: 'caefiss_dur_nyr',
        entityName: "caefiss_aefi_meddras",
        parentEntityName: 'incident',
        parentEntityId: '',
        from: 'caefiss_case_to_aefi_meddra',
        to: 'incidentid', 
        alias: '',
        isMultiSelect: false,
        include: false,
        includeLock: false,
        hideDisplayName: true,
        hideIncludeCheckbox: true,
        wrapped: true
      },
    ]
  }

  public getVaccineComponents() {
    return this.vaccineComponents;
  }

  public getMedraComponents() {
    return this.medraComponents;
  }
}
